version: "3.8"
services:
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  statu_hub:
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_URL=${REDIS_URL}
      - BROADCAST_BUFFER_SIZE=${BROADCAST_BUFFER_SIZE}
      - SERVER_PORT=${SERVER_PORT}
    ports:
      - "3000:3000"
